# -*- coding: utf-8 -*-
"""Artigo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13vlao-PoF9MNjXYTUTUFbmMMn_8qwXms

**Automatic Detection and Quantification of Defective Corn Kernels Using YOLOv8 and Multi-Object Tracking**

Este bloco é um pipeline cientifico voltado para (a) Detecção de grãos defeituosos; (b) Classificação dos defeitos; (c) Rastreamento com ByteTrack;
Contagem sem duplicidade; (d) Geração automática de estatísticas do lote.

**Parte 1 – Download do Dataset de Milho**
"""



!nvidia-smi

#1. Instalação do Yolov8
!pip install ultralytics==8.4.90

from IPython import display
display.clear_output()

# prevent ultralytics from tracking your activity
!yolo settings sync=False

import ultralytics
ultralytics.checks()

import torch
print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="TSzCvpzsORH4ZZNlhbMq")
project = rf.workspace("celsio-assane").project("corn-lycsy-gfkgc")
version = project.version(4)
dataset = version.download("yolov8")

from google.colab import drive
drive.mount('/content/drive')

from ultralytics import YOLO

# Carregar modelo pré-treinado
model = YOLO("yolov8s.pt")

# Treinamento
model.train(
    data=f"{dataset.location}/data.yaml",
    epochs=300,
    imgsz=640,
    batch=16,
    device=0,
    plots=True
)

metrics = model.val()

P = metrics.box.mp
R = metrics.box.mr

F1 = 2 * P * R / (P + R)

print(f"Precision : {P:.4f}")
print(f"Recall    : {R:.4f}")
print(f"F1-score  : {F1:.4f}")

import pandas as pd

# Métricas por classe
P = metrics.box.p
R = metrics.box.r
F1 = 2 * P * R / (P + R)

mAP50 = metrics.box.ap50
mAP5095 = metrics.box.ap

# Nome das classes
classes = ["Bad", "Damaged", "Good"]

# Criar DataFrame
df = pd.DataFrame({
    "Class": classes,
    "Precision": P,
    "Recall": R,
    "F1-score": F1,
    "mAP@0.50": mAP50,
    "mAP@0.50:0.95": mAP5095
})

print(df.round(3))

!ls -R /content/runs/detect

!find /content -type d -name "test"

from ultralytics import YOLO
model = YOLO('/content/runs/detect/train/weights/best.pt')
results = model.predict(
    source='/content/corn-4/test/images',
    conf=0.25,
    save=True,
    show=False
)

import matplotlib.pyplot as plt
import numpy as np

# ----------------------------
# Dados
# ----------------------------
plot_df = df[df["Class"] != "Overall"].copy()

classes = plot_df["Class"]

metrics = {
    "Precision": plot_df["Precision"],
    "Recall": plot_df["Recall"],
    "F1-score": plot_df["F1-score"],
    "mAP@0.50": plot_df["mAP@0.50"],
    "mAP@0.50:0.95": plot_df["mAP@0.50:0.95"]
}

colors = [
    "#4C72B0",
    "#55A868",
    "#C44E52",
    "#8172B3",
    "#CCB974"
]

# ----------------------------
# Figura
# ----------------------------

plt.rcParams.update({
    "font.family":"Arial",
    "font.size":10
})

fig, ax = plt.subplots(figsize=(9,5))

x = np.arange(len(classes))
width = 0.15

bars = []

for i, (metric, values) in enumerate(metrics.items()):

    offset = (i-2)*width

    b = ax.bar(
        x+offset,
        values,
        width,
        label=metric,
        color=colors[i],
        edgecolor='black',
        linewidth=0.4
    )

    bars.append(b)

# ----------------------------
# Valores
# ----------------------------

for group in bars:

    for bar in group:

        h = bar.get_height()

        ax.text(
            bar.get_x()+bar.get_width()/2,
            h+0.01,
            f"{h:.3f}",
            ha='center',
            va='bottom',
            fontsize=8
        )

# ----------------------------
# Estilo
# ----------------------------

ax.set_ylim(0,1.05)

ax.set_ylabel("Metric")

ax.set_xlabel("Class")

ax.set_xticks(x)
ax.set_xticklabels(classes)

ax.grid(axis="y",
        linestyle="--",
        linewidth=0.5,
        alpha=0.35)

ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)

# legenda abaixo

ax.legend(
    loc="upper center",
    bbox_to_anchor=(0.5,-0.16),
    ncol=5,
    frameon=False
)

plt.tight_layout()

# alta resolução

plt.savefig(
    "Figure_PerformanceMetrics.png",
    dpi=600,
    bbox_inches="tight"
)

plt.savefig(
    "Figure_PerformanceMetrics.pdf",
    bbox_inches="tight"
)

plt.savefig(
    "Figure_PerformanceMetrics.svg",
    bbox_inches="tight"
)

plt.show()

import os
import time
import pandas as pd
import matplotlib.pyplot as plt
from ultralytics import YOLO

# Carregar o modelo treinado
model = YOLO('/content/runs/detect/train/weights/best.pt')

# Pasta das imagens de teste
image_dir = "/content/corn-4/test/images"

# Lista de imagens
images = sorted([
    os.path.join(image_dir, img)
    for img in os.listdir(image_dir)
    if img.endswith((".jpg", ".jpeg", ".png"))
])

times = []

print(f"Total de imagens: {len(images)}")

for img in images:

    start = time.perf_counter()

    model.predict(
        source=img,
        conf=0.25,
        verbose=False
    )

    end = time.perf_counter()

    inference_time = (end - start)*1000   # ms

    times.append(inference_time)

# DataFrame
df = pd.DataFrame({
    "Image": [os.path.basename(i) for i in images],
    "Inference_Time_ms": times
})

df.to_csv("inference_times.csv", index=False)

print(df.head())

print("\nInference Time Statistics\n")

print(f"Mean      : {df['Inference_Time_ms'].mean():.2f} ms")
print(f"Median    : {df['Inference_Time_ms'].median():.2f} ms")
print(f"Std Dev   : {df['Inference_Time_ms'].std():.2f} ms")
print(f"Minimum   : {df['Inference_Time_ms'].min():.2f} ms")
print(f"Maximum   : {df['Inference_Time_ms'].max():.2f} ms")

fps = 1000/df['Inference_Time_ms'].mean()

print(f"Average FPS: {fps:.2f}")

# Warm-up
model.predict(source=images[0], verbose=False)

times = []

for img in images:
    start = time.perf_counter()
    model.predict(source=img, verbose=False)
    end = time.perf_counter()
    times.append((end - start) * 1000)

from IPython.display import Image, display

display(Image(filename='runs/detect/train/confusion_matrix.png', width=800))

from IPython.display import Image, display

Image(filename='runs/detect/train/results.png', width=800)

from IPython.display import Image, display

Image(filename='runs/detect/train/val_batch0_pred.jpg', width=800)
Image(filename='runs/detect/train/val_batch1_pred.jpg', width=800)
Image(filename='runs/detect/train/val_batch2_pred.jpg', width=800)

from ultralytics import YOLO

model = YOLO('runs/detect/train/weights/best.pt')

metrics = model.val(data=f"{dataset.location}/data.yaml")

print("Precision:", metrics.box.mp)
print("Recall:", metrics.box.mr)
print("mAP50:", metrics.box.map50)
print("mAP50-95:", metrics.box.map)
print("Loss:", metrics.box.mp)

from IPython.display import Image, display
import os

pred_dir = 'runs/detect/predict'

for img in os.listdir(pred_dir)[:5]:
    display(Image(filename=f"{pred_dir}/{img}", width=600))

import matplotlib.pyplot as plt
import numpy as np

# results é o retorno do model.predict()
# Exemplo:
# results = model.predict(...)

# Número de objetos detectados em cada imagem
num_objects = [len(r.boxes) for r in results]

print("Objetos detectados por imagem:")
print(num_objects)

print(f"Média: {np.mean(num_objects):.2f}")
print(f"Mínimo: {np.min(num_objects)}")
print(f"Máximo: {np.max(num_objects)}")
print(f"Desvio padrão: {np.std(num_objects):.2f}")

# Histograma
plt.figure(figsize=(9,6))

plt.hist(num_objects,
         bins=10,
         edgecolor='black')

plt.xlabel("Number of detected objects per image", fontsize=12)
plt.ylabel("Frequency", fontsize=12)
plt.title("Distribution of Detected Objects per Test Image", fontsize=14)

plt.grid(alpha=0.3)

plt.tight_layout()

plt.savefig("histogram_detected_objects.png", dpi=300)

plt.show()